"use client";

import { useEffect, useState } from "react";
import type { RdtAnalysis } from "../lib/rdt";

type Result={id:string;analysis?:RdtAnalysis;error?:string};

export function AnalysisControl(){
  const [state,setState]=useState<"idle"|"running"|"done"|"error">("idle"),[results,setResults]=useState<Result[]>([]),[message,setMessage]=useState(""),[open,setOpen]=useState(false);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent).detail;setState(detail.state);if(detail.results){setResults(detail.results);if(detail.open)setOpen(true)}if(detail.message){setMessage(detail.message);setOpen(true)}};window.addEventListener("edgelog-analysis-status",handler);return()=>window.removeEventListener("edgelog-analysis-status",handler)},[]);
  const complete=results.filter(r=>r.analysis),scored=complete.filter(r=>r.analysis?.score!==null),failed=results.filter(r=>r.error),average=scored.length?Math.round(scored.reduce((n,r)=>n+(r.analysis?.score||0),0)/scored.length):0;
  return <><button className={`analyze-fab ${state}`} onClick={()=>window.dispatchEvent(new Event("edgelog-run-analysis"))} disabled={state==="running"}>{state==="running"?<><i/>Analyzing aligned bars…</>:state==="done"?`✓ ${complete.length} trades analyzed`:`◎ Analyze actual market data`}</button>{open&&<div className="analysis-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="analysis-results"><button className="analysis-close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">BAR-BY-BAR RDT ANALYSIS</p><h2>{state==="error"?"Analysis could not run":`${complete.length} trades analyzed from historical market data`}</h2>{state==="error"?<p className="analysis-error">{message}</p>:<><div className="analysis-summary"><span><b>{average||"—"}</b><small>AVG VERIFIED SCORE</small></span><span><b>{complete.filter(r=>r.analysis?.status==="complete").length}</b><small>FULLY VERIFIED</small></span><span><b>{failed.length}</b><small>DATA ERRORS</small></span></div><div className="analysis-list">{results.map(result=><article key={result.id}>{result.error?<><div><b>{result.id}</b><small>{result.error}</small></div><em className="unverified">UNVERIFIED</em></>:<AnalysisResult id={result.id} analysis={result.analysis!}/>}</article>)}</div><p className="analysis-footnote">Scores use only verified criteria. Missing sector mapping, insufficient bars, catalysts, and discretionary chart geometry remain explicitly unverified.</p></>}</section></div>}</>
}

function AnalysisResult({id,analysis}:{id:string;analysis:RdtAnalysis}){const pass=analysis.checks.filter(c=>c.status==="pass").length,fail=analysis.checks.filter(c=>c.status==="fail").length,signal=analysis.relativeSignal||(analysis.metrics.intradayRrs!==null&&analysis.metrics.intradayRrs<0?"RW":"RS");return <><div><b>{id} · {analysis.setup}</b><small>{analysis.verdict}</small><span className="metric-row">{signal} vs SPY {analysis.metrics.intradayRrs?.toFixed(2)??"n/a"} · SPY trend {analysis.metrics.spyMovePct?.toFixed(2)??"n/a"}% · RVOL {analysis.metrics.rvol?.toFixed(2)??"n/a"}× · Void {analysis.metrics.voidPct?.toFixed(2)??"n/a"}%</span><details><summary>View computed evidence</summary><ul>{analysis.checks.map(check=><li key={check.key} className={check.status}><b>{check.status}</b><span>{check.label}: {check.value}</span><small>{check.evidence}</small></li>)}</ul><footer>Provider: {analysis.provider} · Entry reconstructed as {new Date(analysis.entryTimeUtc).toLocaleString()}</footer></details></div><div className="analysis-counts"><strong>{analysis.score??"—"}</strong><small>{pass} pass · {fail} fail<br/>{analysis.completeness}% complete</small></div></>}
